### ISSUE TITLE
프로젝트 주제 정하기

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#1]
예측, 분류 관련해서 어떤 것을 프로그래밍 할 지 토의

**Comment by dlcodns** [comment]
제가 생각한 아이디어는 보험 대출 웹페이지입니다. 사람들이 많이 쓰는 은행 3,4개를 정해서 그 은행에서 시행하는 보험이나 대출을 예측, 추천해주는 웹페이지를 생각해보았습니다. 나의 연봉, 대출 상황 등 상황과 정보를 입력하면 그에 맞춰 예측해주는 서비스입니다!

**Comment by KIMSSI22** [comment]
프로젝트에 차별화가 필요할 것 같은데 그 점에서 chat gpt를 이용하면 특색을 줄 수 있을 것 같습니다. gpt api key를 이용하여 주제의 서브 기능으로 상담을 도울 수 있는(재무 상담이나 패션의 트렌드 질문) 기능을 프로그램에 포함 할 수 있다면 좀 더 경쟁력 있는 프로젝트가 될 것 같습니다.

**Comment by troymerai** [comment]
Chat GPT는 제 친구가 한 걸 봤는데, 자료가 많지 않기도하고 세부적인 데이터는 직접 넣어줘야 답해주더라고요. 그래서 좀 더 자료조사가 필요할 꺼 같습니다.

**Comment by troymerai** [comment]
그래서 제가 생각한 아이디어는 가상 피팅 서비스입니다.
클라이언트가 자신의 전신이 나온 사진과 입어보고싶은 옷의 사진을 올리면 두 사진을 합성하여 보내주는 앱서비스입니다.

**Comment by troymerai** [comment]
제 아이디어의 차별점에 대해 말하자면 일단 시중에서 찾아보기 힘듭니다.
어플을 찾아봐도 안경 가상 피팅 어플은 있지만 그냥 옷을 피팅해보는 서비스는 없고 다른 곳도 개발 중입니다.
따라서, 저희가 실제 모습과 옷을 가상 피팅하는 서비스를 빠르게 출시한다면 충분히 차별점이 있다고 생각합니다.
그리고 이번 기회에 딥러닝에 대해 공부해보고 실제 서비스로 배포해보면 많은 걸 배울 수 있을 것이라고 생각합니다.

**Comment by dlcodns** [comment]
대출 보험 서비스도 은행을 3, 4개를 통합해서 정보 적고 예측해주는 서비스 자체가 차별점이라고 생각해요. 제 경우에도 최근에 대출을 받았는데, 여러 은행의 대출 서비스가 많고 그에 따른 필요한 정보들도 많아서 적합한 대출을 찾는데에 막막함을 느꼈거든요

**Comment by dlcodns** [comment]
근데 제가 태윤님 의견에 살짝 설득되는 것 같아요

**Comment by KIMSSI22** [comment]
하하하하 저도 그렇게 듣고 보니 설득 되네요.

**Comment by dlcodns** [comment]
그런데 태윤님이 따로 보내주신 영상 보니까 4, 5개 정도 포크해서 가져오던데 문제가 되지 않을까요???

**Comment by troymerai** [comment]
상대적으로 가벼운 딥러닝 프로젝트는 모델을 가져와서 하는 경우가 많다고 알고있습니다.
그리고 교수님께서 보여주신 예시나 다른 프로젝트들을 봐도 그렇게 하기때문에 괜찮을 거 같습니다.

**Comment by dlcodns** [comment]
딥러닝은 아직 안배워서 쉽지 않을 것 같기도 하고 제 아이디어가 태윤님 것보다 가벼운 편이라서 괜찮을 것 같다고 생각했어요!

**Comment by troymerai** [comment]
다른 사람들 아이디어 보니까 딥러닝을 이용한 프로젝트도 많아보여서 저희도 좀 어렵게 방향을 잡는게 나을 것 같습니다.

**Comment by KIMSSI22** [comment]
맞네요. 저도 채운님 아이디어가 우리가 직접 참여하기에 좋다고 생각해서 마음이 끌렸는데 태윤님 말도 듣고 보니까 아직 서비스를 제공하는 곳이 없다는 점에서 차별점도 있고 저희가 아직 공부해보지 못한 영역을 도전하는 것도 학습에 도움될 것 같습니다.

**Comment by dlcodns** [comment]
저도 태윤님 아이디어 괜찮은 것 같아요..! 그런데 저희는 딥러닝을 아직 안배웠고 잘몰라서, 대부분 태윤님이 생각하시는 방향에 따라갈 것 같은데 생각하신 역할 분배를 비슷하게 잘 해주셨으면 좋겠습니다..!! 저는 정말 열심히 할 자신 있어요.

**Comment by troymerai** [comment]
감사합니다 그럼 이슈 닫고 역할 분배 준비해보겠습니다!
