### ISSUE TITLE
Branch 작업시 원본 레포에서 commit count 안되는 문제

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#10]
원본 레포에서 바로 브랜치 파서 작업하면 작업물 main에 머지할 때까지 commit count안됩니다.
원본 레포에서 포크 떠서 로컬 레포에서 커밋 푸시하고 원본 레포에 풀리퀘 날려주셔야 commit count잡힙니다.

공부한 바에 의하면 이런 흐름입니다.
```
[원본 저장소 상태]
Main (리드미만 있음)
feature_u2net (리드미만 있음)

[포크 뜬 내 로컬 저장소 상태]
Main (리드미만 있음)
feature_u2net (리드미만 있음)

근데 여기서 feature_u2net에서 수정을 하고 push한 다음에,
원본 저장소의 feature_u2net브랜치로 풀리퀘 날림
(아직은 원본 저장소에 commit수 반영 안됨)

원본 저장소에서 풀리퀘 받아줌
(이때 원본 저장소에 commit수 반영됨)

원본 저장소에서는 풀리퀘를 feature_u2net브랜치에 대해서만 받아줬으니까

[원본 저장소 상태]
main(리드미만 있음)
feature_u2net(리드미 + 수정된 파일)
```

결론 : 원본 레포부터 건들지 말고 포크 떠서 풀리퀘 날리자

**Comment by troymerai** [comment]
한번씩 읽고 자신 어싸인 눌러주세요~
(틀린 부분 있으면 답글 달아주세요..)

**Comment by dlcodns** [comment]
좋아요 감사합니다~!

**Comment by KIMSSI22** [comment]
넴넴 감사합니다~~

**Comment by troymerai** [comment]
원본 저장소 오너인 이채운님은 브랜치 파서 하셔도 커밋으로 인정돼서 원본 저장소에서 브랜치 파고 나중에 main 브랜치로 풀리퀘 날리시면 될꺼같습니다

**Comment by dlcodns** [comment]
네 그렇게 하겠습니다 감사합니다

**Comment by troymerai** [comment]
교수님께 여쭤봤는데 포크떠서 하는 건 외부인이 하는 방식이라고 포크 뜨지 말고 원본 저장소에서 브랜치 관리로 해보라고 하셨습니다.
그래서 위에 적은 포크 뜨는 건 잊으셔도됩니다.

근데 결국 마지막에 개인 브랜치에서 메인으로 꼭 머지해야만 커밋수가 인정된다고합니다.

**Comment by troymerai** [comment]
이슈 닫겠습니다!
