### ISSUE TITLE
mysql 데이터베이스에 넣어야 할 데이터 정리

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#12]
뭐 넣어야 할 지 생각나는 거 있으시면 적고 assign 해주세요

**Comment by dlcodns** [comment]
**Table1:  useraccount:   UID**(자동 증가, 중복 금지), **name**(고정), **user_id**(고정, 중복 금지), **password**(가변)
![image](https://user-images.githubusercontent.com/107669084/231342292-f1668f28-7c2b-4105-b62f-3143bdb0ea70.png)

**Comment by troymerai** [comment]
Id값은 INT형으로 해주는게 맞지 않나요?
저 Id가 회원가입할 때 유저가 직접 입력하는 Id면 user_id으로 바꾸고 그냥 Id는 UID로 하는게 나을 것 같습니다.
user_id도 char형만 쓰진 않으니 VARCHAR형, UID는 INT형으로 지정해주는게 나을 것 같습니다.

**Comment by dlcodns** [comment]
네, uid는 유저마다 번호를 부여해주는 id이고 user_id는 로그인 시에 입력하는 id 인가요?

**Comment by dlcodns** [comment]
varchar는 가변형 데이터고 id를 변경하지 못하게 하려고 char로 한 건데, 아이디를 변경할 수 있게 하려는 건가요?

**Comment by troymerai** [comment]
넵 uid는 유저마다 부여해주는 id고 user_id는 로그인 시 입력하는 id입니다.

**Comment by troymerai** [comment]
varchar이랑 char는 제가 헷갈렸던게 맞는거 같습니다.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/107831875/231320880-0ec050f9-b052-47a5-ab63-4056926165eb.png">
그냥 그대로하셔도 될꺼같습니다.

**Comment by dlcodns** [comment]
네 알겠습니다!

**Comment by dlcodns** [comment]
사진 DB 만들겠습니다
