### ISSUE TITLE
UI 디자인 제작

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#15]
이번 프로젝트에서 사용할 UI 디자인을 제작합니다.

**Comment by KIMSSI22** [comment]
디자인 제작 툴은 Figma를 사용할 예정입니다.
따라서 디자인 파일은 FIG 파일로 제작되고  피그마 계정 만드시는 것을 추천드립니다.
웹을 기반으로 하기 때문에 굳이 앱은 설치 안하셔도 됩니다.

**Comment by KIMSSI22** [comment]
현재 임시로 제작된 디자인입니다.
<img width="1686" alt="temp" src="https://user-images.githubusercontent.com/107696062/231482589-c7e4c2de-8614-4b96-bf52-a84fb93dd2c4.png">

**Comment by troymerai** [comment]
디자인 좋습니다. 근데 소셜 로그인은 지금 굳이 안만들어도될 것 같습니다.
일단 도안대로 중간평가까지 최대한 만들어보는게 어떨까요?

**Comment by KIMSSI22** [comment]
그렇군요. 알겠습니다!

**Comment by KIMSSI22** [comment]
<img width="2226" alt="guide" src="https://user-images.githubusercontent.com/107696062/232760964-2b95cedf-74eb-48b8-ac69-304653a5f320.png">
메인 페이지로 가기 전 가이드입니다. 발표전 전체적인 UI 디자인은 필요할 것 같아서 디테일하게 제작은 못할 것 같지만 큰부분은 발표 전까지 제작해서 올리겠습니다.

**Comment by troymerai** [comment]
디자인 좋습니다!

**Comment by dlcodns** [comment]
좋습니다

**Comment by KIMSSI22** [comment]
<img width="1278" alt="main" src="https://user-images.githubusercontent.com/107696062/233735038-402d7bcc-9c82-4031-a334-144a02a8dee8.png">
메인 페이지와 대기 화면입니다. 그.. 대기 화면에 무슨 문구를 넣어야 할지 몰라서 저렇긴 한데 혹시 괜찮은 말 있으면 말해주세요.

**Comment by KIMSSI22** [comment]
<img width="1434" alt="result" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/64132714-fe95-4161-8568-1990945854b3">
몇가지 요소 수정되었습니다.

**Comment by KIMSSI22** [comment]
<img width="2550" alt="guide2" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/4856db8f-543c-4bc0-a1d5-359473fbc886">
가이드 파일 수정되었습니다.

**Comment by KIMSSI22** [comment]
<img width="390" alt="mypage" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/1c6365e2-b387-4821-84a5-f9ef46188400">
마이페이지 화면입니다

**Comment by KIMSSI22** [comment]
<img width="2902" alt="advice" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/36562bed-6266-4f68-a06f-d3206207d62a">
마이페이지 안에 advice의 페이지에 해당하는 화면들입니다.
공지사항과 실험실은  비워두었고 오픈소스 라이선스는 추후 내용을 취합하여 작성하겠습니다.
그리고 개인정보 처리 방침과 서비스 이용 약관은 타 앱 내용을 몇 가지 수정해서 올린 겁니다.

**Comment by KIMSSI22** [comment]
<img width="400" alt="configuration" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/cc73abd6-9294-4695-b3c3-ee40ee80b2da">
설정 화면 입니다.

**Comment by KIMSSI22** [comment]
<img width="1019" alt="modify" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/073c12dc-550b-42ed-953c-f39aa0c3a33b">
회원 정보 및 비밀번호를 수정하는 페이지 입니다.

**Comment by KIMSSI22** [comment]
<img width="1979" alt="logout,unregister" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/ca7e739d-fd3f-4248-b9d5-edfda4ffbce2">
로그아웃과 회원탈퇴 페이지 입니다.

**Comment by KIMSSI22** [comment]
<img width="3798" alt="collection" src="https://github.com/dlcodns/OSP_Prediction/assets/107696062/27264927-aa01-4016-b079-4fe763932086">
시작 페이지와 메인페이지 추가 및 수정했습니다.

**Comment by KIMSSI22** [comment]
![collection](https://github.com/dlcodns/OSP_Prediction/assets/107696062/bd73a3ff-aab2-4716-9f13-30c222dac6aa)
모든 페이지와 그동안 수정한 걸 모두 적용한 취합본입니다.
