### ISSUE TITLE
브랜드 이미지 정하기

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#16]
컬러나 이름이나 디자인 적으로 의견 있으시면 말씀해주세요. 
아래는 제가 임시로 만든 이미지긴 한데 아무래도 대표 컬러나 이름은 같이 정하면 좋을 것 같습니다.

**Comment by KIMSSI22** [comment]
<img width="390" alt="iPhone 14 - 2" src="https://user-images.githubusercontent.com/107696062/231473210-732328e3-c73e-452a-88de-9e440f4a52ee.png">

**Comment by troymerai** [comment]
좋습니다

**Comment by KIMSSI22** [comment]
다른 의견 없으시면 이런 느낌으로 계속 진행하겠습니다. 혹시 진행되는 부분에서도 디자인적 의견 있으시면 UI 제작 이슈에서 코멘트 해주세요.

**Comment by dlcodns** [comment]
이름 어떤 걸로 할 지 생각해볼까용
저는 피팅룸이 좋은 것 같아요

**Comment by troymerai** [comment]
저도 피팅룸 좋습니다

**Comment by KIMSSI22** [comment]
넵. 그럼 대표 색상으로 생각해 두신 거 있으세요? 아니면 혹시 보라색은 좀 부담스럽게 느껴진다는 생각 드나요?
