### ISSUE TITLE
Flutter 파트 분배

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#17]
채운님과 제가 flutter 파트를 분배해서 제작하기로 해서 어느 부분을 맡을 지에 대해 상의가 필요할 것 같습니다. 
UI가 완성될 때까지 여기서 분배에 대한 의견 나누어 보아요!

**Comment by dlcodns** [comment]
일단 지금까지 만든 ui 목록 여기에도 글로 올려주세요!

**Comment by KIMSSI22** [comment]
지금까지 구성된건 시작, 로그인, 회원가입, 가이드, 메인 화면 정도긴 한데 나중에 조금 더 진행되면 정리해서 올리겠습니다!

**Comment by dlcodns** [comment]
저는 시작, 로그인, 회원가입 하고 싶습니다!

**Comment by KIMSSI22** [comment]
넵 알겠습니다

**Comment by KIMSSI22** [comment]
일단 제가 가이드 부분 제작하겠습니다.

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/40bb4f0f-d656-4432-b6bf-db53529997ff)

김민서: 2,3,5
이채운: 1,4,6 하기로 했습니다
