### ISSUE TITLE
8주차 중간 발표 준비

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#18]
![image](https://user-images.githubusercontent.com/107696062/232931433-30ed2463-1c36-40f6-9bcd-3046d364358d.png)

이제 발표 자료를 만들어야 할 것 같습니다. 중간 발표까지에서 필요한 요소는 추진 방법 및 일정까지인데 7~8분 분량의 발표 내용을 준비하려면 서둘러야 할 듯 합니다.

**Comment by KIMSSI22** [comment]
저희 모두 다음주 월화수가 시험 피크라 이번주 토요일까지는 발표자료가 완료되어야 할 것 같습니다.
역할 분담은 대본, ppt, 발표 모두 다 나눠서 하는 건 어떨까요? 발표 분량이 있기도해서 혼자 발표는 힘들기도 하고 나눈다면 차라리 모든 분량을 나눠서 만드는것도 좋을 것 같습니다.

**Comment by dlcodns** [comment]
좋습니다. 저는 내일 시험이 있어서 내일 20일 3시부터 참여하겠습니다ㅜㅜ

**Comment by troymerai** [comment]
각자 개발에서 맡은 파트로 나누나요?

**Comment by dlcodns** [comment]
전체 대본을 적절히 삼등분해서 나눠 발표하는 건 어떨까요?

**Comment by dlcodns** [comment]
시간 초과 30초마다 1점 감점

**Comment by KIMSSI22** [comment]
괜찮은 것 같습니다. 개발을 맡은 파트별로 준비하다보면 통일성이 떨어질 것 같아서 
필요성, problem / solution / 차별성, 추진 방법 및 일정
이런식으로 삼등분하는 건 어떨까요?

**Comment by troymerai** [comment]
좋습니다.

**Comment by troymerai** [comment]
제가 솔루션 파트 맡아도 될까요?
모델 구현하는 과정에서 기존에서 수정한 게 꽤 있어서 다른 분이 맡으시면 설명하는데 시간이 또 들 것 같습니다.

**Comment by KIMSSI22** [comment]
넵 알겠습니다. 태윤님은 솔루션 부분 준비 부탁드려요.

**Comment by dlcodns** [comment]
제가 필요성이랑 problem 맡아도 될까요

**Comment by KIMSSI22** [comment]
채운님과 상의해서 채운님은 필요성, problem을 하고 저는 차별성, 추진 방법 및 일정을 맡기로 했습니다.

**Comment by troymerai** [comment]
넵넵 감사합니다

**Comment by dlcodns** [comment]
그럼 대본을 목요일까지 작성해서 올리는 건 어떨까요? ppt는 각자 맡은 대본으로 만들어서 토요일 낮 12시까지 어떠세요

**Comment by troymerai** [comment]
넵넵 좋습니다

**Comment by troymerai** [comment]
시간 되실 때 #19 에 각자 개발 현황 적어주시면 감사하겠습니다

**Comment by KIMSSI22** [comment]
넵 알겠습니다.

**Comment by troymerai** [comment]
솔루션 파트 대본입니다! #19 에 개발현황 추가해주시면 고쳐보겠습니다.

### [제안하는 방법 및 구현 방향]

**#피피티 1페이지**
(서비스 아키텍쳐 수정해서 피피티에 넣기)
피팅룸의 아키텍쳐에 대해 설명하겠습니다.
클라이언트가 옷 사진과 자신의 사진을 입력하면 서버에서 돌아가는 세가지의 딥러닝 모델을 통해 순서대로 옷 마스킹 이미지, 휴먼 세그멘테이션 이미지, 이를 토대로한 가상 피팅 이미지를 생성합니다. 데이터베이스에 해당 데이터를 저장해두고 클라이언트에게 반환하여 가상 피팅 서비스를 제공합니다.

**#피피티 2페이지**
이를 구현하기 위해 
플러터를 이용해 안드로이드/ios에서 모두 사용 가능한 어플을 만들 예정이고
데이터베이스는 mysql을 사용할 예정입니다.
회원가입과 로그인 기능은 php로 구현할 예정이고
모델 서빙 기능은 fastapi로 구현할 예정입니다.
딥러닝 모델은 다음과 같이 오픈소스로 공개된 파이토치 모델들을 사용할 예정입니다.
(모델 명과 사용 이유 피피티에 넣기)

### [현재까지의 구현 상황]

**#피피티 3페이지**
다음으로 저희 팀의 구현 현황에 대해 설명하겠습니다.
프론트엔드 구현에 앞서 피그마로 로그인/회원가입 페이지, 온보딩 페이지, 메인 페이지, 결과 페이지의 UI디자인을 정했습니다.
그리고 mysql 디비에 유저 정보를 담을 데이터테이블을 생성하였습니다.
딥러닝 모델은 로컬과 코랩에서 테스트를 해봤는데
로컬에서는 옷 마스킹 모델만 성공하고 다른 모델들은 실패하였습니다. 
그 원인으로는 모델을 돌리는 데 필요한 한 패키지가 리눅스 환경에서만 컴파일되기때문인 것으로 생각하고있습니다.
코랩에서는 세 모델 모두 테스트에 성공하였습니다.
로컬에서 api로 변환하는 것은 모델이 돌아가지 않았기에 아직 시도하지 않았습니다.
코랩에서는 ngrok으로 api 외부 개방, 이미지 업로드 기능 및 세가지 모델 구현에 성공하였으며 결과 이미지 반환 기능까지 완성하여 postman으로 테스트까지 완료한 상황입니다.

**Comment by dlcodns** [comment]
problem에 인풋 아웃풋이 뭘 말하는 걸까요?

**Comment by troymerai** [comment]
저희한텐 사용자가 넣어주는 이미지가 인풋이고 아웃풋은 가상피팅한 이미지 아닐까요?

**Comment by dlcodns** [comment]
아하 problem이 단순히 문제점이라고 생각했는데 그냥 저희 프로젝트 주제군요 감사합니다

**Comment by troymerai** [comment]
필요성에 problem이 있어서 그렇게 생각했는데 다시 보니 헷갈리네요.. 민서님 의견도 들어보면 좋을 것 같습니다

**Comment by dlcodns** [comment]
어플 이름 민서님이 만든 대로 Fitting Room으로 정하는 거 어떠세요? 저는 좋은 것 같아요

**Comment by dlcodns** [comment]
필요성에 [이 프로젝트가 왜 중요한 지] 써야 하는데 쓸 만한 말이 있을까요? 
이런 어플을 찾을 수 없다라는 차별점을 쓰면 뒤에 차별점이랑 겹치고, 
우리가 이 프로젝트를 하면 개발능력을 올릴 수 있다고 쓰는 건 교수님 의도가 아닌 것 같고 그르네여

**Comment by KIMSSI22** [comment]
그러게요. 저도 코멘트 읽으면서 생각해보고 있는데 아리송한 부분이 있어요

**Comment by KIMSSI22** [comment]
그리고 혹시 어플 이름에 대한 이야기는 이슈 #16 에서 해요! 
의견이 없는 줄 알고 닫았는데 다시 리오픈 했습니다!

**Comment by KIMSSI22** [comment]
필요성에서 이 프로젝트가 왜 중요한 지에 대해서는 약간 현대인이 추구하는 효율에 대한 이야기는 어떨까요? 
요즘에는 외출을 해서 시간과 체력을 사용하기 보다는 당장의 자리에서 결정하고 확인하는 것을 바라는 시대니까 우리의 프로젝트는 이런 시기에 가장 어울리고 따라서 필요하다 어쩌구 하면서..

**Comment by dlcodns** [comment]
천재세요?

**Comment by KIMSSI22** [comment]
하하 감사함니다

**Comment by dlcodns** [comment]
ppt 만들어봤는데 괜찮은 지 봐주세요(완성 아님)
[이채운 중간발표.pdf](https://github.com/dlcodns/OSP_Prediction/files/11300159/default.pdf) -  업데이트 함

[인삿말]
#피피티 1페이지
안녕하세요. 칭찬주시조의 발표를 시작하겠습니다. 저희가 생각한 아이디어는 가상 피팅 서비스 Fitting Room입니다.

[목차]
#피피티 2페이지
먼저 목차를 소개하겠습니다. 순서는 필요성, problem, 차별성, Solution, 추진 방법 및 일정 순으로 발표하겠습니다.

[필요성]
#피피티 3페이지
먼저 필요성입니다. 평소 우리는 옷을 살 때 나와 어울리는지, 색상은 피부색과 맞는지 등을 생각하며 옷을 고릅니다. 온라인으로 구매하려 하면 직접 입어보지 못하고, 오프라인으로 구매하고  해도 가고 오는 시간이 아까운데다 단추 없는 상의나 원피스는 구매 전 피팅하지 못하게 합니다. 이런 경우 고심해서 고른다 해도 직접 입어보고 살 수 없기 때문에, 사고 나서 안 어울려 후회한 경험이 한 번쯤 다들 있으실 겁니다. 그러나 옷을 가상으로 입혀주는 어플리케이션이 있다면 고민이나 시간낭비 없이 이 Problem을 해결할 수 있습니다. 이 프로젝트가 중요한 이유입니다. 오늘날 우리는 스마트폰으로 금융, 구매, 여가, 집 관리 등 대부분의 일을 처리할 수 있고, 일을 쉽게 처리할 수 있게 하는 기능들도 나날이 개발되고 있습니다. 시간과 체력을 사용하기 보다는 스마트폰을 활용해 당장의 자리에서 결정하고 확인하는 것을 추구하는 시대이기 때문에,  가상 피팅 서비스 프로젝트는 이런 시기에 적합하고 필요한 어플리케이션이라고 생각합니다. 

[Problem]
#피피티 4페이지
다음은 Problem입니다. 저희가 생각한 problem의 프로젝트명은 Fitting Room입니다. 가상 피팅 서비스인 Fitting Room은 스마트폰을 이용해 옷을 미리 입어보는, 나만의 작은 탈의실을 만들 수 있는 딥러닝을 활용한 어플리케이션입니다. Input과 Output으로는, 클라이언트가 자신의 전신이 나온 사진과 입어보고 싶은 옷의 사진을 Input으로 올립니다. 그러면 Fitting room 프로그램은 클라이언트의 몸을 분석하여 머리카락과 피부 등을 구분할 수 있게 합니다. 또한 제출한 옷의 누끼를 따서 저장해 놓습니다. 이렇게 처리한 모델 사진과 옷 사진을 합성하여 Output으로 합성사진을 내보내는 서비스입니다. 화면 오른쪽 표와 같이 합성이 됩니다.

**Comment by KIMSSI22** [comment]
발표 대본입니다!
 
[차별성]
다음은 저희 팀의 차별성입니다.
일단 가상 피팅 서비스라는 개념 자체가 나온지 얼마 안되었기도 하였고 따라서 아직은 많은 곳이 개발 단계에 머물러 있습니다. 그리고 무엇보다 현재 가상피팅 서비스 업계에서 가장 초점이 맞춰진 것은 VR을 이용하여 완전한 가상에서 더 완성도 높고 더 현실에 가까운 서비스 제공하는 것 입니다. 
그러나 저희는 가상 피팅 서비스를 휴대폰에 담았습니다. 물론 VR이 제공하는 피팅 서비스에 비한다면 상대적으로 간단한 기술이기 때문에 '이거는 하위호환 아니야?'라고 생각하실 지도 모르겠습니다. 하지만 그만큼 저희의 프로젝트는 사용자에게 쉽고 접근성 높게 다가갈 것 입니다. 아무리 기술이 빠르게 발전해 나간다해도 VR은 보급화 되어있지 않고 따라서 이를 이용한 가상 피팅 서비스의 상용화하기란 기대하기 어려운 상황입니다. 그렇기에 저희는 현실과 가상의 합의점을 찾았고 이 서비스를 당장 모든 사람의 손 안에 들어올 수 있다면 어떨까를 생각했습니다. 그 결과 저희는 휴대폰 안에 서비스 담기로하였고 현실과 가상의 과도에서 경쟁력있는 차별성을 가진 프로젝트를 계획하였습니다.

[추진 방법 및 일정]
추진 방법 및 일정 입니다. 
다음 화면은 역할의 분배인데 보시는 것 처럼 이채운 학생은 DB, Localhost, flutter이고 이태윤 학생은 deeplearning model - Python, fastAPI를 맡았고 김민서 학생은 PHP, UI 디자인, flutter를 맡으면서 역할의 관련성이 있는 방향으로 분배했습니다. 따라서 개인적으로 진행 가능한 부분은 이슈에서 정리하면서 진행하고 역할이 겹치거나 다른 팀원의 의견이 필요한 경우에는 팀원을 어싸인해서 이슈를 통해 의견을 나누며 조율해서 프로젝트를 완성시킬 계획입니다. 
그리고 이에 따른 프로젝트 진행 일정으로는 다음과 같습니다. (개인이 계획한 일정 수렴 #21 ) 
이채운 학생 같은 경우에는 데이터베이스를 먼저 시작하고 그다음 플러터, 로컬 서버 작업을 점진적으로 추가하여 진행할 것이고 이태윤 학생은 로컬과 코랩에서 딥러닝 모델 테스트를 진행하고 코랩에서  API 구현을 작업 후 쭉 로컬에서 딥러닝 모델 테스트를 하고 로컬에서  API 구현을 하는 것으로 마무리할 예정입니다. 그리고 김민서 학생의 경우 UI 디자인을 어느 정도 마친 후 flutter 작업을 시작하고 중간에 PHP를 병행하다 flutter를 작업하고 마무리할 예정입니다.
당장의 일정을 이렇게 세웠지만 이번 프로젝트에서 더 빨리 끝나거나 더 잘하는 학생이 진행에 어려움이 있는 학생을 도와주기도 하면서 팀 프로젝트라는 것에 어울리게 유연한 일정을 진행할 것 입니다. 

지금까지 앱을 통한 가상 피팅 서비스 프로젝트에 대해 발표한 칭찬주시조였습니다. 감사합니다.

**Comment by KIMSSI22** [comment]
개인적으로 읽어 보았을 때 2분 20초에서 30초 사이에 끝나시나요? 이 정도 시간대를 최대한 안 넘겨야 7~8분에 맞추기 쉬울 것 같아요.

**Comment by troymerai** [comment]
넵넵

**Comment by dlcodns** [comment]
저기서 말한 problem이  이 프로젝트 아닐까요? 
필요성: problem(프로젝트)을 풀어야 하는 이유, 
problem: problem(프로젝트) 소개 및 인풋 아웃풋 정리

**Comment by dlcodns** [comment]
대본 보통의 속도로 읽어봤습니다
채운: 2분17
태윤: 2분 정도
민서: 2분04 (개인이 계획한 일정 제외한 값)

7-8분이니까 한 사람당 2분-2분30초까지 늘리면 될 것 같습니다

**Comment by troymerai** [comment]
넵 2분정도로 수정했습니다

**Comment by dlcodns** [comment]
넵 민서님이 일정표까지 넣고 셋 다  여유롭게 발표하면 7분 넘길 것 같습니다! 민서님이 올리면 확인해 볼게요

**Comment by troymerai** [comment]
넵넵

**Comment by KIMSSI22** [comment]
추가 및 수정했습니다~

**Comment by dlcodns** [comment]
[칭찬주시조 중간발표 ppt.pdf](https://github.com/dlcodns/OSP_Prediction/files/11321790/ppt.pdf)
확인 부탁드립니다

**Comment by dlcodns** [comment]
ppt가져가면 폰트나 크기 변할 수도 있으니까 자료실에도 pdf올리는 거 어떠세요??

**Comment by troymerai** [comment]
좋습니다

**Comment by KIMSSI22** [comment]
좋아요~

**Comment by dlcodns** [comment]
저희 이제 발표 순서를 정해야 하는데 대본 짠 대로 가면 민서- 태윤- 민서 순이니까 그 부분을 조정하면 좋을 것 같아요

**Comment by dlcodns** [comment]
태윤님이 차별점 솔루션 말하고 그 뒤에 민서님이 말하는 건 어떨까요? 다른 생각있으신가욥?

**Comment by KIMSSI22** [comment]
음 저도 생각해 봤는데 태윤님이 차별점이랑 솔루션을 다 하시면 호흡이 많이 길어지는 것 같아서요

**Comment by KIMSSI22** [comment]
근데 또 솔루션을 나누기는 애매하네요..

**Comment by KIMSSI22** [comment]
좀 애매한 것 같으면 그냥 왔다갔다 제가 2번하는 것도 크게 이상하지 않을 것 같은데 그냥 할까요?

**Comment by dlcodns** [comment]
넵 좋습니다

**Comment by troymerai** [comment]
차별성 + 제안하는 방법 및 구현방향
현황 + 추진 계획

나눈다면 이렇게 나눠야할꺼 같은데 민서님 어떤 거 하고싶으세요?
차피 대본대로 읽기만 하면 될꺼같아서

**Comment by troymerai** [comment]
앗 그럼 그냥 그대로..

**Comment by KIMSSI22** [comment]
앗 음 다들 뭐가 더 좋으세요?

**Comment by KIMSSI22** [comment]
저는 사실 둘 다 상관없습니다!

**Comment by troymerai** [comment]
저도 상관없습니다 그냥 그대로 가시져

**Comment by dlcodns** [comment]
ㅎㅎ 좋습니당!

**Comment by dlcodns** [comment]
#피피티 1페이지
안녕하세요. 칭찬주시조의 발표를 시작하겠습니다. 저희가 생각한 아이디어는 가상 피팅 서비스 Fitting Room입니다.

[목차]
#피피티 2페이지
먼저 목차를 소개하겠습니다. 순서는 필요성, problem, 차별성, Solution, 추진 방법 및 일정 순으로 발표하겠습니다.

[필요성]
#피피티 3페이지
첫번째로 필요성입니다. 평소 우리는 옷을 살 때 나와 어울리는지, 색상은 피부색과 맞는지 등을 생각하며 옷을 고릅니다. 온라인으로 구매하려 하면 직접 입어보지 못하고, 오프라인으로 구매하려고 해도 가고 오는 시간이 아까운 데다 단추 없는 상의나 원피스는 구매 전 피팅하지 못하게 합니다. 이런 경우 고심해서 고른다 해도 직접 입어보고 살 수 없기 때문에, 사고 나서 안 어울려 후회한 경험이 한 번쯤 다들 있으실 겁니다. 그러나 옷을 가상으로 입혀주는 어플리케이션이 있다면 고민이나 시간낭비 없이 이 Problem을 해결할 수 있습니다. 다음으로 이 프로젝트가 중요한 이유입니다. 오늘날 우리는 스마트폰으로 금융, 구매, 여가, 집 관리 등 대부분의 일을 처리할 수 있고, 일을 쉽게 처리할 수 있게 하는 기능들도 나날이 개발되고 있습니다. 시간과 체력을 사용하기 보다는 스마트폰을 활용해 당장의 자리에서 결정하고 확인하는 것을 추구하는 시대이기 때문에, 가상 피팅 서비스 프로젝트는 이런 시기에 적합하고 필요한 어플리케이션이라고 생각합니다.

[Problem]
#피피티 4페이지
다음은 Problem입니다. 먼저 저희가 생각한 problem의 프로젝트명은 Fitting Room입니다. 가상 피팅 서비스인 Fitting Room은 스마트폰을 이용해 옷을 미리 입어보는, 나만의 작은 탈의실을 만들 수 있는 딥러닝을 활용한 어플리케이션입니다. Input과 Output으로는, 클라이언트가 자신의 전신이 나온 사진과 입어보고 싶은 옷의 사진을 Input으로 올립니다. 그러면 Fitting room 프로그램은 클라이언트의 몸을 분석하여 머리카락과 피부 등을 구분할 수 있게 합니다. 또한 제출한 옷의 누끼를 따서 저장해 놓습니다. 이렇게 처리한 모델 사진과 옷 사진을 합성하여 Output으로 합성사진을 내보내는 서비스입니다. 화면 오른쪽 표와 같이 합성이 됩니다.

[차별성]
#피피티 5페이지
다음은 저희 팀의 차별성입니다.
일단 가상 피팅 서비스라는 개념 자체가 나온지 얼마 안되었기도 하였고 따라서 아직은 많은 곳이 개발 단계에 머물러 있습니다. 그리고 무엇보다 현재 가상피팅 서비스 업계에서 가장 초점이 맞춰진 것은 VR을 이용하여 완전한 가상에서 더 완성도 높고 더 현실에 가까운 서비스 제공하는 것 입니다.
그러나 저희는 가상 피팅 서비스를 휴대폰에 담았습니다. 물론 VR이 제공하는 피팅 서비스에 비한다면 상대적으로 간단한 기술이기 때문에 '이거는 하위호환 아니야?'라고 생각하실 지도 모르겠습니다. 하지만 그만큼 저희의 프로젝트는 사용자에게 쉽고 접근성 높게 다가갈 것 입니다. 아무리 기술이 빠르게 발전해 나간다해도 VR은 보급화 되어있지 않고 따라서 이를 이용한 가상 피팅 서비스의 상용화하기란 기대하기 어려운 상황입니다. 그렇기에 저희는 현실과 가상의 합의점을 찾았고 이 서비스를 당장 모든 사람의 손 안에 들어올 수 있다면 어떨까를 생각했습니다. 그 결과 저희는 휴대폰 안에 서비스 담기로하였고 현실과 가상의 과도에서 경쟁력있는 차별성을 가진 프로젝트를 계획하였습니다.

[Solution]
#피피티 8페이지
(서비스 아키텍쳐 수정해서 피피티에 넣기)
피팅룸의 아키텍쳐에 대해 설명하겠습니다.
클라이언트가 옷 사진과 자신의 사진을 입력하면 서버에서 돌아가는 세가지의 딥러닝 모델을 통해 순서대로 옷 마스킹 이미지, 휴먼 세그멘테이션 이미지, 이를 토대로한 가상 피팅 이미지를 생성합니다. 데이터베이스에 해당 데이터를 저장해두고 클라이언트에게 반환하여 가상 피팅 서비스를 제공합니다.

#피피티 9페이지
이를 구현하기 위해
플러터를 이용해 안드로이드/ios에서 모두 사용 가능한 어플을 만들 예정이고
데이터베이스는 mysql을 사용할 예정입니다.
회원가입과 로그인 기능은 php로 구현할 예정이고
모델 서빙 기능은 fastapi로 구현할 예정입니다.
딥러닝 모델은 다음과 같이 오픈소스로 공개된 파이토치 모델들을 사용할 예정입니다.
(모델 명과 사용 이유 피피티에 넣기)

[현재까지의 구현 상황]
#피피티 10페이지
다음으로 저희 팀의 구현 현황에 대해 설명하겠습니다.
프론트엔드 구현에 앞서 피그마로 로그인/회원가입 페이지, 온보딩 페이지, 메인 페이지, 결과 페이지의 UI디자인을 정했습니다.
그리고 mysql 디비에 유저 정보를 담을 데이터테이블을 생성하였습니다.
딥러닝 모델은 로컬과 코랩에서 테스트를 해봤는데
로컬에서는 옷 마스킹 모델만 성공하고 다른 모델들은 실패하였습니다.
그 원인으로는 모델을 돌리는 데 필요한 한 패키지가 리눅스 환경에서만 컴파일되기때문인 것으로 생각하고있습니다.
코랩에서는 세 모델 모두 테스트에 성공하였습니다.
로컬에서 api로 변환하는 것은 모델이 돌아가지 않았기에 아직 시도하지 않았습니다.
코랩에서는 ngrok으로 api 외부 개방, 이미지 업로드 기능 및 세가지 모델 구현에 성공하였으며 결과 이미지 반환 기능까지 완성하여 postman으로 테스트까지 완료한 상황입니다.


[추진 방법 및 일정]
#피피티 11페이지
추진 방법 및 일정 입니다.
다음 화면은 역할의 분배인데 보시는 것 처럼 이채운 학생은 DB, Localhost, flutter이고 이태윤 학생은 deeplearning model - Python, fastAPI를 맡았고 김민서 학생은 PHP, UI 디자인, flutter를 맡으면서 역할의 관련성이 있는 방향으로 분배했습니다. 따라서 개인적으로 진행 가능한 부분은 이슈에서 정리하면서 진행하고 역할이 겹치거나 다른 팀원의 의견이 필요한 경우에는 팀원을 어싸인해서 이슈를 통해 의견을 나누며 조율해서 프로젝트를 완성시킬 계획입니다.

#피피티 12페이지
그리고 이에 따른 프로젝트 진행 일정으로는 다음과 같습니다. (개인이 계획한 일정 수렴 #21 )
이채운 학생 같은 경우에는 데이터베이스를 먼저 시작하고 그다음 플러터, 로컬 서버 작업을 점진적으로 추가하여 진행할 것이고 이태윤 학생은 로컬과 코랩에서 딥러닝 모델 테스트를 진행하고 코랩에서 API 구현을 작업 후 쭉 로컬에서 딥러닝 모델 테스트를 하고 로컬에서 API 구현을 하는 것으로 마무리할 예정입니다. 그리고 김민서 학생의 경우 UI 디자인을 어느 정도 마친 후 flutter 작업을 시작하고 중간에 PHP를 병행하다 flutter를 작업하고 마무리할 예정입니다.
당장의 일정을 이렇게 세웠지만 이번 프로젝트에서 더 빨리 끝나거나 더 잘하는 학생이 진행에 어려움이 있는 학생을 도와주기도 하면서 팀 프로젝트라는 것에 어울리게 유연한 일정을 진행할 것 입니다.

#피피티 13페이지
지금까지 앱을 통한 가상 피팅 서비스 프로젝트에 대해 발표한 칭찬주시조였습니다. 감사합니다.

**Comment by dlcodns** [comment]
보이스톡으로 시간 확인해볼까요??

**Comment by KIMSSI22** [comment]
제가 지금 기숙사라 통화는 조금 어려울것 같아요ㅜㅜ

**Comment by dlcodns** [comment]
그럼 각자 해보고 시간 재서 여기에 올리는 건 어떠세요?

**Comment by troymerai** [comment]
넵넵

**Comment by KIMSSI22** [comment]
넴

**Comment by troymerai** [comment]
저 2분 정도 나왔습니다

**Comment by KIMSSI22** [comment]
2분 54초입니다.

**Comment by dlcodns** [comment]
저 2분 17초 나왔습니다.

**Comment by dlcodns** [comment]
태윤님 몇분 몇초인가요?

**Comment by troymerai** [comment]
2분 3초입니다

**Comment by dlcodns** [comment]
아 2분 조금 안넘어도 1분 50초 정도면 되네욥

**Comment by dlcodns** [comment]
저희 그럼 7분 조금 넘기는 거니까 말만 빠르게 안하고 이대로 진행하면 될 것 같아요!

**Comment by troymerai** [comment]
넵넵

**Comment by dlcodns** [comment]
태윤님 ppt 4페이지에 넣을 사진 세 개 보내주실 수 잇나요? 모델 사진, 옷사진, 합성사진

**Comment by troymerai** [comment]
아 넵넵 보내드리겠습니다

**Comment by dlcodns** [comment]
그럼 수정 후에 바로 피피티 올리겠습니다! 수고하셨습니당 내일 화이팅!!

**Comment by troymerai** [comment]
수고하셨습니다~

**Comment by KIMSSI22** [comment]
넵 감사합니다~!

**Comment by dlcodns** [comment]
최종 pdf
[칭찬주시조 중간발표 ppt.pdf](https://github.com/dlcodns/OSP_Prediction/files/11322075/ppt.pdf)
