### ISSUE TITLE
중간 발표까지 구현 상황

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#19]
각자 중간 발표까지 코드나 디자인적으로 구현한 것 적어주시면 감사하겠습니다

**Comment by troymerai** [comment]
**개발 진행 상황**

[개발 파트]
1. 딥러닝 모델 
- 로컬
- 코랩

2. api
- 로컬
- 코랩

[딥러닝 모델 - 로컬]
- ✅ u2net(옷 마스킹 모델) 구현 - 성공
- ❌ 휴먼 세그멘테이션 모델 구현 - 실패
- ❌ ACGPN(이미지 합성) 모델 구현 - 실패

[딥러닝 모델 - 코랩]
- ✅ u2net(옷 마스킹 모델) 구현 - 성공
- ✅ 휴먼 세그멘테이션 모델 구현 - 성공
- ✅ ACGPN(이미지 합성) 모델 구현 - 성공

[api - 로컬]
- ✅ 파일 생성 기능 구현 - 성공
- ✅ 이미지 업로드 기능 구현 - 성공
- ngrok으로 api개방 - 시도안함
- u2net(옷 마스킹 모델) 구현 - 시도안함
- 휴먼 세그멘테이션 모델 구현 - 시도안함
- ACGPN(이미지 합성) 모델 구현 - 시도안함   

[api - 코랩]
- ✅ ngrok으로 api개방 - 성공
- ✅ 이미지 업로드 기능 구현 - 성공
- ✅ u2net(옷 마스킹 모델) 구현 - 성공
- ✅ 휴먼 세그멘테이션 모델 구현 - 성공
- ✅ ACGPN(이미지 합성) 모델 구현 - 성공
- ✅ 결과 이미지 반환 - 성공

[어려웠던 점]
딥러닝 모델, fastapi를 처음 다뤄보고 코랩으로 api를 만드는 것도 처음 해봐서 시간이 오래 걸림
로컬에서 딥러닝 모델을 구현하는 과정에서는 환경변수 설정이 굉장히 까다로웠고 힘들었음

**Comment by dlcodns** [comment]
**개발 진행 상황** - 구현할 때 어려움 추가했습니다

[개발 파트]
1. DB 
2. localhost
3. flutter 프론트 개발

[DB] - 새로 추가할 데이터테이블이 이슈에 추가되면 바로 생성할 예정
1. 유저 정보 데이터테이블 생성
   - UID, name, user_id, password

[로컬 서버 작업] - 컴퓨터공학과 선배에게 개발 순서에 대해 물어보았는데 (DB - app - 백엔드) 순서로 주로 한다고 들음. DB와 futter를 먼저 할 예정


[flutter]


[전체적인 어려움] - 세 개 다 처음 다뤄보기 때문에 강의를 미리 듣거나 연습해보느라 개발을 시작하기가 어려웠음.

**Comment by troymerai** [comment]
구현할 때 어려움있으시면 이거도 적어주시면 감사하겠습니다아..
(예를 들어 fastapi코드로 변환할 때 파이썬에 능숙하지 못해 시간이 지체되었다.)

**Comment by KIMSSI22** [comment]
[개발 파트]
  1. UI 디자인
  2. flutter
  3. PHP


[UI 디자인]
  - 로그인, 회원가입 페이지O
  - 가이드 페이지O
  - 메인(선택) 페이지O
  - 반환 페이지O
  - 결과 다시보기 페이지O
  - 유저 페이지x
  - 알림 페이지x
  - 디테일x

[PHP]
  - 로그인/회원가입 로직x
  - 이미지 업로드 로직x 

[flutter]
 

[어려움]
  - 모두 이전까지는 이용한 적이 없기 때문에 사전 학습이 필요해서 바로 개발에 들어갈 수 없었음. 그리고 디자인의 경우에도 디자인을 배워본 적이 없기 때문에 어떤 디자인이 사용 친화적인 건지 구분하기가 어려웠음
