### ISSUE TITLE
기능 명세서 정의 및 역할 분배

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#2]
기능 명세서 정의 및 역할 분배

**Comment by troymerai** [comment]
**기능 명세서 정의 및 역할 분배**

[UI 디자인]

    - 회원가입 페이지 디자인
    - 메인 페이지 디자인
    - 로딩 페이지 디자인
    - 이미지 선택 페이지 디자인
    - 이미지 반환 페이지 디자인
    - 이미지 전체 리스트 디자인
    - Github Readme 작성

[프론트엔드]

1. Flutter
    - 기본 UI 구현
    - 로그인/회원가입 기능
    - 이미지 선택 기능
    - 로딩 화면 구현
    - 이미지 반환 후 저장 기능
    - 이미지 전체 리스트뷰 구현

[백엔드]

1. DB - mySQL
    - DB테이블 설계 및 생성

2. Localhost
    - 유저 파일 만들고 유저 이미지 파일 다운로드
    - 반환 받은 이미지 파일 다운로드

3. DeepLearning Model - Python
    - Colab에서 DB에 저장된 이미지 경로 받아오기
    - 모델 구현
    - 모델 오류 수정
    - 모델과 fastAPI 웹서버 연결하기

[API]

1. PHP
    - 로그인/회원가입 로직
    - 이미지 업로드 로직

2. fastAPI
    - 모델과 연결
    - 모델에서 반환값 받아서 client에 반환

**Comment by troymerai** [comment]
<img width="960" alt="OPS-2023" src="https://user-images.githubusercontent.com/107831875/227435547-f4308700-64d7-448c-9291-237db46dcce4.png">

기본 아키텍쳐 입니다!

**Comment by dlcodns** [comment]
안녕하세요 3시니까 시작할까용

**Comment by KIMSSI22** [comment]
넵

**Comment by troymerai** [comment]
넵넵

**Comment by dlcodns** [comment]
일단 각자 하고 싶은 파트 있으신가요??

**Comment by dlcodns** [comment]
저는 FE 플루터랑 BE의 데이터베이스 관심있습니다

**Comment by troymerai** [comment]
저는 딥러닝 모델 구현과 fastAPI를 이용한 웹서버 구축 파트를 하고싶습니다

**Comment by dlcodns** [comment]
이미 말한 거 얘기해도 되니까 편하게 말하세여

**Comment by KIMSSI22** [comment]
저는 php랑 먼가 다 잘 나누어져 있는 것 같아서 디자인해도 좋아요. 근데 좀 구릴 수도 있음

**Comment by dlcodns** [comment]
그럼 로컬 호스트 남았는데

**Comment by KIMSSI22** [comment]
그것도 제가..?

**Comment by dlcodns** [comment]
태윤님

**Comment by troymerai** [comment]
그거 데이터베이스 하시는 분이 같이 하시는게 편할꺼에요

**Comment by dlcodns** [comment]
로컬 호스트 빼고 분배가 됐는데 저희 셋 중에 제일.... 난이도 낮거나 빨리

**Comment by dlcodns** [comment]
오홍 알겠습니당 제가 할게용

**Comment by troymerai** [comment]
채운님이 데이터베이스랑 로컬 서버 구축하시고 민서님이 플러터 좀 도와주시면 될꺼같습니다.

**Comment by KIMSSI22** [comment]
넵 알겠습니다

**Comment by dlcodns** [comment]
그럼 제가 플러터 하고 민서님이 제 플러터를 도와주는 건가요?

**Comment by troymerai** [comment]
네넵 처음부터 같이 파트 나눠서 하셔도 되고 그렇게 해도 될 것 같습니다

**Comment by dlcodns** [comment]
프론트엔드를 해보고 싶었어서 그롬 제가 하구 민서 도움을 받을게요!!

**Comment by troymerai** [comment]
넵넵

**Comment by dlcodns** [comment]
최종파트 정리해서 여기 올릴게요

**Comment by KIMSSI22** [comment]
넵

**Comment by KIMSSI22** [comment]
제 근데 약간 저 할일이 적지 않나요..?

**Comment by dlcodns** [comment]
김민서: UI 디자인, PHP, Flutter
이태윤: DeepLearning Model - Python, fastAPI
이채운: Flutter, DB - mySQL, Localhost
