### ISSUE TITLE
프로젝트 진행 일정

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#21]
발표에 작성될 일정을 계획한 것을 적어주세요.
표나 그래프 형식으로 나타낼 것이라 자세히 적지 않으셔도 돼요.

이채운 -  DB, Localhost, flutter
이태윤 - deeplearning model - Python, fastAPI
김민서 - PHP, UI 디자인, flutter

**Comment by KIMSSI22** [comment]
1주차: -
2주차: -
3주차: 팀 결성, 주제 탐색
4주차: 주제 결정 및 계획, 짧은 발표
5주차: 사전학습
6주차: 사전 학습, UI 디자인
7주차: UI 디자인
8주차: 중간 발표
9주차: Flutter, UI 디자인
10주차: PHP, UI 디자인
11주차: PHP, flutter
12주차: PHP, flutter
13주차: flutter
14주차: flutter, UI 디자인
15주차: 기말 발표

**Comment by troymerai** [comment]
**[현황]**
1주차: -
2주차: -
3주차: 팀 결성, 주제 탐색
4주차: 주제 결정 및 계획, 짧은 발표
5주차: 딥러닝 모델 로컬 테스트
6주차: 딥러닝 모델 로컬 및 코랩 테스트
7주차: 코랩에서 api 구현
8주차: 코랩에서 api 구현 및 중간 발표

**[중간 발표 이후 계획]**
1. 다른 팀원 개발 도움
2. 로컬에서 딥러닝 모델 테스트
3. 로컬에서 api 구현

9주차: 다른 팀원 개발 도움
10주차: 로컬에서 딥러닝 모델 테스트
11주차: 로컬에서 딥러닝 모델 테스트
12주차: 로컬에서 딥러닝 모델 테스트
13주차: 로컬에서 딥러닝 모델 테스트 
14주차: 로컬에서 api 구현
15주차: 기말 발표

**Comment by KIMSSI22** [comment]
그 중간 이후 일정도 주차 별로 나타내 주실 수 있나요? 그냥 상상으로 대충 이때 쯤에는 이거하고 있겠다 하는 느낌이요.

**Comment by troymerai** [comment]
수정했습니다

**Comment by dlcodns** [comment]
1주차: -
2주차: -
3주차: 팀 결성, 주제 탐색
4주차: 주제 결정 및 계획, 짧은 발표
5주차: 사전학습
6주차: 사전 학습, 데이터베이스
7주차: 데이터베이스
8주차: 중간 발표
9주차: Flutter, 데이터베이스
10주차: Flutter, 데이터베이스
11주차: Flutter, 데이터베이스, 로컬 서버 작업
12주차: Flutter, 데이터베이스, 로컬 서버 작업
13주차: Flutter, 데이터베이스, 로컬 서버 작업
14주차: Flutter, 데이터베이스, 로컬 서버 작업
15주차: 기말 발표
