### ISSUE TITLE
Flutter 시작 화면) Icon 이미지 버튼 크기 조절 오류

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#23]
door 사진은 width로 조절 가능하였으나,
icon 버튼 이미지는 width를 바꿔봐도 같은 크기로만 나오는 오류 발생했습니다.
![image](https://user-images.githubusercontent.com/107669084/235859332-cbd911bc-5b8b-449d-b2ff-4469cc98e411.png)

**Comment by troymerai** [comment]
sizedbox위젯 컨테이너로 바꿔보시고 color값 지정해줘서 확인해보실래요?
sizedbox는 color지정 못해서 헷갈릴 수 있습니다

**Comment by dlcodns** [comment]
![image](https://user-images.githubusercontent.com/107669084/236181120-5c2575d4-89f0-40a6-8569-f984fa4fc5a8.png)
해결 했습니다! 꿀팁 감사합니다^^

**Comment by dlcodns** [comment]
![image](https://user-images.githubusercontent.com/107669084/236181247-55396e6d-3f90-4cc8-91d8-1ec040ee53de.png)
