### ISSUE TITLE
5/21까지 끝내기 위한 계획 짜기

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#24]
각자 맡은 부분 언제까지 할 지 여기 올려놓는 건 어떨까요?
얼마나 했는지 알 수 있게 그 날까지 완수 했으면 그때마다 ✅체크해 놓으면 좋을 것 같아요.

또 flutter처럼 나눠서 하는 활동은 서로 얘기 나눠가면서 일정 조율하면 좋을 것 같습니다!

예시)
5/7까지) 00000 완료하기✅
5/11까지) 00000 완료하기✅
5/17까지) 00000 완료하기

**Comment by dlcodns** [comment]
**[계획표]**

5/7까지)

**Comment by dlcodns** [comment]
**[계획표]**

5/11까지)
- [x] start_select 화면 만들기

5/1_까지) flutter 완료
- [x] join 화면 만들기
- [ ] login 화면 만들기
- [ ]

**Comment by troymerai** [comment]
[계획표]

5/11까지)
컴퓨터 구조 시험때문에 못함

5/12까지)

- [x] 플러터 이미지 받는 ui 기능 구현
- [x] 플러터에 api연결
- [x] 전체 테스트

5월 16일자 기준 기존 계획 완료했습니다.

5/21까지)

- [ ] api 주석 달기
- [ ] 플러터 테스트 코드 주석 달기
- [ ] 플러터 UI 수정
- [ ] superresolution 모델 api에 넣기
- [ ] 플러터에서 이미지 다운로드 기능 구현
- [ ] 리드미 작성

**Comment by KIMSSI22** [comment]
[계획표]

5/14까지)
- UI 디자인

**Comment by dlcodns** [comment]
민서님이 ui 작업을 14일이나 15일까지 마치면 좋을 것 같아요! 
그리고 데이터 베이스에 뭐 넣어야 할 지 생각하신 거 있으면 #12 에 댓 달아주세요

**Comment by dlcodns** [comment]
언제까지 해주실 수 있나요?

**Comment by KIMSSI22** [comment]
넵 UI 작업은 14일까지 끝낼게요!

**Comment by dlcodns** [comment]
그럼 저희 flutter는 16일까지 할까요?
