### ISSUE TITLE
Flutter 진행상황

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#25]
<만든 Flutter 사진 올리는 곳>

완료면 완료라 적어주시고
수정할 부분 있으면 의견 제시해주세요!

**Comment by dlcodns** [comment]
[로그인 회원가입]

**Comment by dlcodns** [comment]
[회원가입]

**Comment by troymerai** [comment]
UI 만드실 때 위젯 반응형으로 개발하고 계시죠?
화면 커지거나 작아질 때 깨지거나 글씨 이상해지면 고쳐야합니다..!

**Comment by dlcodns** [comment]
넵!!!! 고치겠습니다..!!

**Comment by dlcodns** [comment]
**1번 파트**
[start] - 완료
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/84c5724f-c171-42ec-a35c-a80de9fecc9d.png" width="300">

[start_select] - 완료
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/ed228be2-076d-4335-a3e1-af166434c273.png" width="300">

[join] - [완료] 
DB 연결이 안돼서 코드 자체적으로 이메일- test@example.com, 비밀번호 - password1이 이미 있는 것으로 설정해 놨습니다.
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/531e44ef-e931-420d-8dd9-c42e66236675.png" width="300">

[login] - [완료]
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/321189b1-27a5-4427-8329-dc1ed170c91c.png" width="300">

[celebration] - [완료]
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/380a7fa5-c905-4f6e-b744-63e58a09bb51.png" width="300">

**Comment by dlcodns** [comment]
**4번파트** - [완료]
[result]https://annhee.tistory.com/58
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/f7004978-eaeb-42b7-82b7-1d02637950c6.png" width="300">

[review_1] - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/499f6bbd-2cbf-408c-9c59-1e1cf4c01e39.png" width= "300">


[review_2] - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/c701e9ef-811c-4bea-864b-352f24cdba2d.png" width = "300">

**Comment by dlcodns** [comment]
**6번파트** - [완료]
[setting]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/b65c9bcc-2526-4c9e-835f-c4aabefb5b6f.png" width = "300">

[modify] - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/8f0a5108-82cf-4f71-a49d-0b9704159214" width = "300">

[pwmodify] - [완료]
비밀번호 일단 password1로 했습니다 - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/bfa0aa81-49f7-4a3e-a295-830beb92b26f.png" width = "300">

[logout] - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/db340d98-d65a-4123-bf9e-2a367027998f.png" width = "300">

[unregister] - [완료]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/b49ee853-aa75-4ae2-8e07-8243c7be0187.png" width = "300">

**Comment by KIMSSI22** [comment]
**2번 파트**
[guide]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/6070e32e-8d67-4de6-bb1b-f5e9bd511ce4)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/13043672-425a-4f2c-a6e0-2bdb8d8137e7)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/f3d7e1fb-131b-49d0-a5e8-fb4491992bca)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/4dada887-9b96-4882-aac5-16cf81323b2c)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/a3dec07b-a1cc-4d2b-a6c4-8e3c22a8350b)

**Comment by KIMSSI22** [comment]
**3번 파트**
[main]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/179f44a2-e51a-4d43-bdbb-9178c2542d41)
