### ISSUE TITLE
모듈 적용 안되는 오류 발생

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#27]
환경변수 설정했음
cmd에서 적용도 완료함

그런데 실행 안되는 오류 발생했습니다. 해결해보겠습니다. (start.dart)

![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/3e2177b9-558f-45e4-bc64-0bbf5e28e8fa)

![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/342da4ce-209f-42a2-8c4e-3f8fa31b9cd8)

**Comment by troymerai** [comment]
pubspec.yaml파일 내용 중에
dependencies:
      flutter:
확인하셨나요?

**Comment by dlcodns** [comment]
네 확인 했습니다! 
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/bc151804-c3f7-49b4-84bf-79221d859b1c)

**Comment by troymerai** [comment]
터미널 창에 flutter clean치시고 실행 완료되면 flutter pub get 쳐보시겠어요?

**Comment by dlcodns** [comment]
도와주셔서 감사합니다 
입력했습니다!
<img src="https://github.com/dlcodns/OSP_Prediction/assets/107669084/65e353ba-34f1-4aca-b420-d7df2070ef3e" width="400">

**Comment by troymerai** [comment]
해결된건가요?

**Comment by dlcodns** [comment]
아니요 그대로 입니다

**Comment by dlcodns** [comment]
근데 이 부분을 잘 모르겠는데 implicit가 뭔지 모르겠어요. 일단 저 때 cmd에 flutter pub get 입력만 했고요
https://pub.dev/packages/flutter_screenutil/install
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/09459fd9-73d3-4a87-8075-85f0366f6902)

**Comment by troymerai** [comment]
모듈 설치는 잘 됐는데 왜 인식을 못하는지 저도 잘 모르겠습니다.
IDE한번 껐다가 켜보실래요? 가끔 IDE에서 인식 못하는 경우도 있어서..

**Comment by troymerai** [comment]
implicit flutter pub get은 아마 처음에 패키지 install 했을 때 자동으로 flutter pub get이 돌아가는 걸 말하는 걸겁니다.
지금은 패키지 설치는 잘된거 같아서 신경쓰실 필요 없습니다.

**Comment by troymerai** [comment]
<img width="650" alt="image" src="https://github.com/dlcodns/OSP_Prediction/assets/107831875/d3b2b413-bf3c-4109-ad4c-858d1338288d">

> https://pub.dev/packages/flutter_screenutil<br/> 

해당 패키지 공식문서 찾아보면 designSize는 가능한데 allowingFontScaling은 못쓰는거 같습니다.
allowingFontScaling없애보실래요?

**Comment by dlcodns** [comment]
혹시 MediaQuery 했으면 이거 안해도 되는건가요?

**Comment by troymerai** [comment]
넵

**Comment by dlcodns** [comment]
넵
