### ISSUE TITLE
4주차 발표 준비

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#3]
4주차에 할 발표문과 PPT 한 장 준비합시다.

**Comment by dlcodns** [comment]
안녕하세요

**Comment by KIMSSI22** [comment]
안녕하세요

**Comment by troymerai** [comment]
안녕하세요

**Comment by dlcodns** [comment]
발표에 어떤 걸 넣으면 좋을까요!~

**Comment by troymerai** [comment]
아키텍쳐 넣는건 어떤가요?

**Comment by KIMSSI22** [comment]
오 좋아용

**Comment by dlcodns** [comment]
아키텍쳐를 피피티화면에 띄울까요?

**Comment by troymerai** [comment]
전 그게 좋을 것 같습니다

**Comment by dlcodns** [comment]
그대로 올릴까요 아니면 보완해서?

**Comment by troymerai** [comment]
아 좀 보완해서 하는게 나을 것 같습니다..

**Comment by KIMSSI22** [comment]
아하 그렇군요

**Comment by dlcodns** [comment]
1. 우리 주제(예측), 아이디어
2. 어플 형식
3.

**Comment by dlcodns** [comment]
맡은 역할도 적을까요?

**Comment by KIMSSI22** [comment]
그러면 너무 길어지고 1장으로는 부족할 것 같아요

**Comment by troymerai** [comment]
네 그냥 저렇게만 해도 좋을 거 같습니다

**Comment by dlcodns** [comment]
좋습니당

**Comment by dlcodns** [comment]
그럼 발표문을 적어보아요..ㅎㅎ

**Comment by dlcodns** [comment]
안녕하세요 칭찬주시조의 발표를 맡은 김민서입니다. 저희 조에서 생각한 주제는 가상 피팅 서비스입니다.

**Comment by dlcodns** [comment]
![image](https://user-images.githubusercontent.com/107669084/227759248-29506e69-9233-4c16-a87b-d4ee394236df.png)

**Comment by troymerai** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/107831875/227759551-63b1469c-5ffa-413a-baf8-ac02044f1bf5.png">

아키텍쳐 수정본입니다!

**Comment by dlcodns** [comment]
안녕하세요 칭찬주시조의 발표를 맡은 김민서입니다. 저희 조에서 생각한 주제는 가상 피팅 서비스입니다. 클라이언트가 자신의 전신이 나온 사진과 입어보고싶은 옷의 사진을 올리면 두 사진을 합성하여 보내주는 딥러닝을 활용한 서비스입니다. 
서비스 구현 방식은 안드로이드와 ios로 어플로 만들 계획입니다.
이 아이디어의 차별점으로는 시중이나 어플에서 찾아보기 힘들고, 이러한 서비스가 개발 중이라는 점입니다. 따라서, 저희가 실제 모습과 옷을 가상 피팅하는 서비스를 빠르게 출시한다면 충분히 차별점이 있다고 생각해 이 아이디어를 채택했습니다.

**Comment by troymerai** [comment]
아키텍쳐 부분 스크립트입니다

아키텍쳐를 보시면 
클라이언트가 회원가입과 로그인 요청을 보내면 php웹서버를 통해 mysql데이터베이스에 접근하여 처리합니다.
로그인이 완료된 클라이언트가 가상 피팅 요청을 보내면 해당 이미지들을 php웹서버를 통해 local저장소에 저장하고 mysql데이터베이스에 이미지 주소를 넣어줍니다. 그리고 fastAPI웹서버를 통해 딥러닝 모델로 해당 이미지 주소를 보내주고 가공된 데이터를 local 저장소에 저장하고 데이터베이스에 이미지 주소를 넣어줍니다. 그리고 해당 이미지를 클라이언트에게 반환해줍니다.

**Comment by KIMSSI22** [comment]
![4주차 발표](https://user-images.githubusercontent.com/107696062/227760498-bead9f87-8a05-4683-ac53-8040199cba34.png)

**Comment by KIMSSI22** [comment]
안녕하세요. 칭찬주시조의 발표를 맡은 김민서입니다. 저희 조가 생각한 주제는 가상 피팅 서비스입니다. 클라이언트가 자신의 전신이 나온 사진과 입어보고 싶은 옷의 사진을 올리면 두 사진을 합성하여 보내주는, 딥러닝을 활용한 서비스입니다.
서비스 구현 방식은 안드로이드와 ios로 제공할 계획입니다.
이 아이디어의 차별점으로는 아직까지는 시중에서 찾아보기 힘들고, 이러한 서비스가 개발 단계라는 점입니다. 따라서, 저희가 실제 모습에 옷을 가상 피팅하는 서비스를 빠르게 출시한다면 차별점은 충분히 있다고 생각해 이 아이디어를 채택했습니다.
오른쪽 아키텍쳐에 대해 설명하겠습니다. 클라이언트가 회원가입과 로그인 요청을 보내면 php웹서버를 통해 mysql데이터베이스에 접근하여 처리합니다.
로그인이 완료된 클라이언트가 가상 피팅 요청을 보내면 해당 이미지들은 php웹서버를 통해 local저장소에 저장하고 mysql데이터베이스에 이미지 주소를 넣어줍니다. 그리고 fastAPI웹서버를 통해 딥러닝 모델로 해당 이미지 주소를 보내주고 가공된 데이터를 local 저장소에 저장하고 데이터베이스에 이미지 주소를 넣어줍니다. 그리고 해당 이미지를 클라이언트에게 반환해줌으로 시스템이 운영됩니다.
지금까지 저희의 아이디어 소개와 아키텍쳐에 대해 발표했습니다. 들어주셔서 감사합니다~(꾸벅)
