### ISSUE TITLE
UI 디자인 점검

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#31]
![collection](https://github.com/dlcodns/OSP_Prediction/assets/107696062/9da89348-bf4f-4107-a5f9-479302c241bb)
UI 디자인을 완료했습니다. 보시면서 혹시 수정사항이나 추가사항 있으시면 말씀해주세요. 그리고 오픈소스 라이선스 페이지에 입력해야하는 내용있으면 알려주세요.

**Comment by dlcodns** [comment]
좋은 것 같습니다

**Comment by dlcodns** [comment]
로그인 후 들어가지는 페이지는 어떤 건지, 거기서 뭘 누르면 어디로 들어가지는지 정리가 필요한 것 같습니다

**Comment by dlcodns** [comment]
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/3d219361-2ece-4c78-aecf-21494d69ad9c.png" width="300">
여기서 메인페이지로 가는 버튼 만들까요?

**Comment by KIMSSI22** [comment]
회원가입 버튼을 누르면 회원가입-> 축하 -> 가이드 -> 메인페이지
로그인 버튼을 누르면 로그인 -> 메인페이지
입니다.
