### ISSUE TITLE
Flutter UI 제작

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#32]
flutter로 UI 제작하는 과정을 기록하겠습니다. 주로 commit 참조 남기고 간단한 설명 정도 일 것 같습니다.

**Comment by KIMSSI22** [comment]
guide.dart와 Yaml 파일 옵션 정리해서 세팅했습니다.
그리고 commit 과정에서 폴더 정리가 이상하게 돼서 다시 정리해서 올리고 삭제하면서 불필요한 commit 2회가 늘었습니다.

**Comment by KIMSSI22** [comment]
Expanded 사용해서 반응형으로 확장 가능하게 하였습니다.

**Comment by dlcodns** [comment]
저희 flutter 맞춰야 하는 부분 얘기할게요.

1. MediaQuery 설정
https://www.youtube.com/watch?v=MyFi3N75l8k
#37 

2. 반응형으로 만들기
https://seosh817.tistory.com/83

3. 페이지 간 이동 방법 네비게이터로 하기 
```dart
onPressed: (){Navigator.push(
                              context,
                              MaterialPageRoute(builder: (context)=>StartSelect()));}
```

**Comment by KIMSSI22** [comment]
아하, 넵 알겠습니다!

**Comment by KIMSSI22** [comment]
guide ui 제작했습니다. 아이콘만 사용하려던 자리에 탭바를 이용하여 아이콘을 넣었습니다.

**Comment by KIMSSI22** [comment]
mainpage와 mypage flutter 제작했습니다.
