### ISSUE TITLE
navigator 적용 안되는 문제 발생

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#33]
start페이지에서 시작하기 누르면 start_select 로 가는 네비게이터가 안먹힘.

![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/ba36d9df-3b30-4797-8914-eadcc38bd916)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/ad9bab85-9eca-4c79-bf7a-9eba356a6e55)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/840e735a-9ffb-4a4b-bbdd-5a5b06f7fea0)

오류는 이렇습니다
더 찾아보겠습니다

**Comment by dlcodns** [comment]
/
/
/

**Comment by dlcodns** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by dlcodns** [comment]
```c++

```

**Comment by dlcodns** [comment]
- [ ] ㄴㄴ

**Comment by troymerai** [comment]
지금 1,2 파일만 이동 안되는거 맞나요? 4개 파일 전부 다 같이 안돌아가지 않나요?

**Comment by dlcodns** [comment]
네 다 안돌아가는데 일단 다른 ui 만들어 놓고 있어요! 네비게이터 해보고 내일 말씀드릴게요

**Comment by troymerai** [comment]
넵넵
