### ISSUE TITLE
사이즈 조정해주는 기능 사용하려 는데 문제가 있습니다

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#37]
https://www.youtube.com/watch?v=TEIyMX1us3U
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/02742f1d-7caf-4640-b2ad-fb7fd40f3813)
나머지는 오류가 없는데 이 부분에서 오류가 뜹니다

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/16ce8e4a-6d2f-4744-b333-9ada52114646)
찾아보다가 rethrow를 넣어보니 whenNotZero 오류는 풀렸는데 rethrow 오류가 생겼습니다.
오류: A rethrow must be inside of a catch clause. (Documentation)  Try moving the expression into a catch clause, or using a 'throw' expression.
더 찾아볼게요

**Comment by troymerai** [comment]
영상에서처럼 futurebuilder를 사용할 필요는 없을 꺼 같습니다.
그냥 기존에 하던대로 width와 height를 쓰는데 width, height 값을 mediaquery로 지정해주면 사용자 화면에 맞게 조정이 될껍니다.

**Comment by troymerai** [comment]
https://github.com/Hyunjiiing/OSS-TeamProject/blob/main/troymerai/flutter%20UI/prototype/keunalarm/lib/src/pages/clubpage.dart

여기 참고하시면 될 것 같습니다.

**Comment by dlcodns** [comment]
감사합니다!ㅎㅎㅎ
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/d7d7c9ab-0728-4e9f-80c0-7741aea4aaff)

**Comment by dlcodns** [comment]
태윤님 이미지파일 height에 MediaQuery.of(context).size.height
이렇게 적으면 화면 세로크기에 맞춰서 꽉 차게 나오는 거 맞나요..?
