### ISSUE TITLE
브랜치명 규칙 정하기(+커밋 규칙 공지)

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#4]

**Comment by dlcodns** [comment]
![image](https://user-images.githubusercontent.com/107669084/229359828-739fee56-97aa-4036-b8af-43fe5753851b.png)

**Comment by troymerai** [comment]
각자 개발, 시험에 사용할 브랜치 명이랑 main에 병합하기 전에 마지막으로 체크하는 공용 브랜치같은 거 파려면 약속해두는게 나을 것 같습니다

**Comment by troymerai** [comment]
![image](https://user-images.githubusercontent.com/107831875/229360098-affd46e8-667e-4bf6-9e43-45275e9bf2f2.png)
이런 식으로 하면 어떨까요?

**Comment by dlcodns** [comment]
좋습니다. 교수님께서 브랜치 이름은 무조건 "Feature_작업내용"으로 적으라고 하셨으니까 
**Feature_(이름 이니셜)** - 이 안에 여러 기능 나눠 만들기, **Feature_develop(이니셜)**, **Feature_release(이니셜)**, main=master니까 냅두기
이런 식으로 만들까요? 아니면 다른 생각 있으신가요

**Comment by dlcodns** [comment]
그리고 hotfix는 각자 만드는 건가요 아니면 레포에 하나만 두는 건가용?

**Comment by troymerai** [comment]
좋습니다

**Comment by KIMSSI22** [comment]
좋습니다. 그 외에 커밋 타입에 따른 규칙은
feat : 새로운 기능 추가
fix : 버그 수정
docs : 문서 수정
style : 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
refactor : 코드 리펙토링
test : 테스트 코드, 리펙토링 테스트 코드 추가
chore : 빌드 업무 수정, 패키지 매니저 수정
이렇게 하는게 대표적인 것 같은데 저희도 이렇게 할까요?

**Comment by KIMSSI22** [comment]
그리고 커밋 명 앞에 이슈 번호를 붙이면서 관리하는 것도 좋을 것 같습니다.

**Comment by troymerai** [comment]
좋습니다

**Comment by dlcodns** [comment]
좋습니당
