### ISSUE TITLE
임포트 계속 오류가 남

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#40]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/0be35eb1-8ca3-48f7-b31e-e4159e059da1)
dart파일 잘 넣고 import 경로도 제대로 한 것 같은데 import 에러가 자꾸 뜹니다

**Comment by troymerai** [comment]
파일 구조 나오는 스샷 찍어서 올려주실래요?

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/ceb3c63e-ccf9-41cc-a387-7222292b04ea)
import 'package:result/windows/mybutton.dart';
import 'package:result/mybutton.dart';
둘다 오류가 뜹니다!

**Comment by troymerai** [comment]
mybutton.dart 파일이 windows파일 안에 있나요?

**Comment by dlcodns** [comment]
앗 플러터 상에서 저렇게 보이길래 혹시나 해서 저렇게도 해봤는데 windows안에 없네요..!
그냥 result 파일 안에 있어요. 근데 import 'package:result/mybutton.dart'; 로 해도 안되네요
<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/b8711327-da9e-46c7-be97-7e298da426f7.png" width = "600">

**Comment by troymerai** [comment]
result/windows/mybutton.dart 는 result 폴더 안에 windows 폴더 안에 있는 mybutton.dart 파일이라는 뜻입니다.
result폴더 밑에 mybutton.dart 파일이 있으면 result/mybutton.dart 라고 하면 될 것 같습니다.

**Comment by dlcodns** [comment]
잘못 보고 windows 아래 있는 줄 알았네요ㅜㅜ  
바로 위 제 답장에  import 'package:result/windows/mybutton.dart'; 라고 적었던 건 오타였어요

그렇게 해봤는데 안되네요.. 더 찾아볼게요 감사합니다
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/93dd0074-da4f-4a8a-9f95-c5624b643fc9)
