### ISSUE TITLE
mediaquery와 appabar에 대한 이슈

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#52]
저도 중간에 appbar 관련 실수하다 알았는데 채운님 코드도 그런 부분이 있길래 이슈로 알려드립니다.

먼저 채운님이 mediaquery가 쓰인 코드에는 safearea를 사용하지 않으셨는데 이거는 아마 저희가 참고했던 영상에서 safearea 길이를 출력하고 직접 코드내에서 제외 숫자를 주면서 결론적으로는 오류가 생기셔서 사용하지 않으신 것 같습니다. 근데 그러면 실제 화면에서 아이콘의 짤림이나 원하는 비율로 안보일 수 있습니다. 그래서 앱바의 아이콘이나 텍스트의 높이를 따로 설정 해주셔야 할 것 같습니다.

**Comment by KIMSSI22** [comment]
참고로 저는 메인화면 구성할 때는 50과 45로 했는데 저희가 비슷한 부분인 메인페이지와 설정페이지 부분에서는 43을 띄워 주시고 작업해주시면 좋을 것 같습니다.

**Comment by KIMSSI22** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/bac5af85-1022-41ce-b0ed-8ae123e31f09)
이이콘 설정하실 때 edgeinsets 이용해서 43에 맞춰주시고 위에 참조한 이슈도 한번 봐주세요.

**Comment by dlcodns** [comment]
아이콘이 버튼일 때랑 그냥 아이콘일 때랑 크기가 달라서 각 페이지마다 아이콘 위치가 달라질 수도 있을 것 같아요. 혹시 그런 문제가 생기면 두 경우에 edgeinset을 얼마나 할지 따로 명시해야 할 것 같습니다! 감사합니다.

**Comment by dlcodns** [comment]
말씀하신 대로 설정 부분 바꿔보았습니다! 배경색이랑 body는 신경쓰지 말고 앱바만 봐주세요.

괜찮으시면 버튼 아닌 아이콘은 이 코드대로 고정했으면 합니다. text앞에 띄어쓰기까지요

<img src = "https://github.com/dlcodns/OSP_Prediction/assets/107669084/eded4de1-2a5c-45e4-a82e-58e857da5f6e.ong" width = "300">

```dart
appBar: AppBar(
          toolbarHeight: 100,
          elevation: 4,
          shadowColor: Color(0xffE6E6E6),
          backgroundColor: Color(0xffFFFFFF),
          title: Padding(
            padding: EdgeInsets.only(right:12.0,top:43),
            child: Row(
              children: const [
                Icon(Icons.settings, color: Color(0xff404040), size: 30,              ),
                Text('  설정',
                  style: TextStyle(
                      fontSize: 24,
                      color: Color(0xff404040),
                      fontWeight: FontWeight.bold
                  ),)
              ],
            ),
          ),
        ),
```

**Comment by KIMSSI22** [comment]
넵 알겠습니다
