### ISSUE TITLE
flutter elevation에 대한 이슈

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#53]
채운님과 제가 appbar 제작하는 과정이 있는데 디자인을 보시면 아래 그림자가 들어갑니다.

기존에도 그림자가 있긴 하지만 그림자의 고도와 색깔을 따로 설정해 주시면 좋을 것 같습니다. 
참고로 메인 페이지에는 그림자가 포함되지 않아 0입니다.

**Comment by KIMSSI22** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/ff46176b-3783-4788-a0c0-89fb75873ea8)
고도는 4, 색은 0xffE6E6E6으로 설정해 주세요!

**Comment by dlcodns** [comment]
확인했습니다
