### ISSUE TITLE
Navigator 및 import 이용 방법

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#55]
채운님이 Navigator랑  import로 오류가 계속 생기시는 것 같아서 방법과 원인에 대한 이슈 작성해보겠습니다.
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/4e405a24-24bc-44cb-990f-81864138041c)
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/5294f585-473b-4049-b630-2426f9e8a99f)

Navigator를 이용할 때 주의해야 하는 점은 경로를 잘 작성했나 입니다. 근데 처음 import 작성할 때 조금 적으면 자동 완성을 추천할 건데 그거 쓰시는게 정확합니다.

그리고 이동하셨을 때 작성하신 파일을 전체를 출력하고 싶으시다면 그 파일의 최상위 class 명을 넣어주셔야 합니다. 하위 class를  넣으시면 일부분만 출력됩니다. 또 class 명이 중복되지 않는 것도 고려해 주세요.

**Comment by KIMSSI22** [comment]
채운님이 올리신 이슈 #33 를 보았을 때 문제가 된다고 생각되는 부분은 import에서 경로를 잘못 주신 것 같다고 생각이 듭니다. 
pakage: pratice/screen/start_select.dart에서
pakage: pratice/start_select.dart으로 수정해 보세용

그리고 #40 에서 오류가 난 이유로는 파일 명 안에 대괄호가 있다면 경로로 대괄호 이름을 사용해야 합니다.
6_result -> result

**Comment by KIMSSI22** [comment]
근데 import를 작성할 때 정상적인 경로를 작성하고 있다면 자동완성이 되어서 이렇게 까지 오류가 길게 나진 않았을 것 같습니다. 그래서 드는 또다른 생각은 채운님 스샷을 보니까 dart 파일이 lib 밖에 나와있는데 이게 아주 결정적인 원인 같습니다. 하나는 lib 안이고 하나는 lib 밖이라서 오류가 생기는 것 같아요. 꼭 모든 dart 파일은 lib 안에 넣어주세요!

**Comment by dlcodns** [comment]
넵 페이지 전부 대강 만들고 시도해볼게요 감사합니다! 닫지 말아주세요

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/522adbac-4a64-4257-9c7a-3c23cc50deee)
ㅠㅠㅠㅠ

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/ad474380-e485-4eda-8816-9b0dfa655c37)
엥 뭐죠... 참고로 이거 네비게이터 아니고 기능활용으로 쓴거예요..
그리고 mybutton은 저장을 눌렀을 때 저장되었습니다 문구가 나오게 하는 기능입니다..(사실 없어도 돼요)
```dart
import 'package:flutter/material.dart';

class MyButton extends StatefulWidget {
  @override
  _MyButtonState createState() => _MyButtonState();
}

class _MyButtonState extends State<MyButton> {
  bool _showMessage = false;

  void _handleButtonPress() {
    setState(() {
      _showMessage = true;
    });

    Future.delayed(Duration(seconds: 2), () {
      setState(() {
        _showMessage = false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          onPressed: _handleButtonPress,
          child: Text('버튼'),
        ),
        SizedBox(height: 16),
        _showMessage
            ? Text('저장이 완료되었습니다.')
            : SizedBox.shrink(),
      ],
    );
  }
}
```

**Comment by dlcodns** [comment]
하나로 합쳐봤는데 문구가 안 뜨네요. 그냥 없이 가겠습니다.
그리고 자동완성 꿀팁 정말 감사합니다!!

**Comment by KIMSSI22** [comment]
알겠습니다. 그리고 임포트 되셨다니 굿이네영
