### ISSUE TITLE
php 역할에 대한 질문

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#56]
@troymerai 
민서님 담당인 php 역할이 회원가입, 로그인 로직 구현, 이미지 업로드 로직 구현이라고 알고 있습니다.
제 flutter 역할에  회원가입, 로그인 완성된 이미지를 앱에 업로드하는 부분이 포함되어 있는데 제가 flutter에서 어디까지 구현해 놔야 할지 잘 모르겠습니다.

지금까지 만들었고 앞으로 만들어야 할 것은 아래와 같습니다.(더 있으면 수정 추가해주세요)
얇은 글씨가 제가 해야 할 것들이고,
굵은 글씨가 제가 해야 하는지 php 담당이 해야 하는지 잘 모르겠는 것들입니다!!
 
굵은 글씨 중에 php 담당의 역할이 있는지 답변해주셨으면 합니다.

1. 회원가입:
    - 이메일
      - [x] 이메일 입력창
      - [x] 이메일 구조 정규표현식으로 확인
      - [ ] **[db에 있는 이메일인지 확인(php없어서 지금x)]**

    - 비밀번호 
      - [x] 비밀번호 입력창
      - [x] 비밀번호 안 보이게 처리함
      - [x] 비밀번호 구조 정규표현식으로 확인
      - [x] 비밀번호 2차 확인 시 틀렸을 때 경고
      - [ ] **[비밀번호 md5 설정(php와 db 필요)]**

    - 다음 버튼
      - [x] 필수 동의 안 눌렀을 때 못넘기게 하기
      - [x] 이메일과 비번 구조 틀렸을 때 경고
      - [ ] **[이미 있는 이메일 경고(php와 db 필요)]**
      - [ ] **[회원가입 가능할 때 가입 축하 페이지로 이동시키기(php와 db 필요)]**
      - [ ] **[등록된 이메일과 비밀번호 DB로 보내기]**

2. 로그인
      - [x] 이메일이 정규표현식이 아닐 때 로그인 시 경고
      - [ ] **[비밀번호가 틀렸을 때 로그인 시 경고(php와 db 필요)]**
      - [ ] **[이메일이 DB에 없을 때 로그인 시 경고(php와 db 필요)]**
      - [ ] **[이메일에 따른 비밀번호가 DB에 없을 때 로그인 시 경고(php와 db 필요)]**

3. 완성 이미지 업로드
    - [ ] **[이미지 완성하려면 DB, php 필요]**
    - [ ] **[완성 이미지 DB에 저장(review에서 다시보기 할 수 있게)(php와 db 필요)]**

**Comment by dlcodns** [comment]
그리고 DB를 할 때 mysql work bench에서 하는 게 좋을지 xampp에서 하는 게 좋을 지 추천해주시면 감사하겠습니다..!!

**Comment by troymerai** [comment]
다음 버튼, 로그인 부분만 구현하시면 될 것 같습니다.
저는 mtsql work bench에서 ERD만 그려보고 xampp로 구현했었습니다.

**Comment by dlcodns** [comment]
네 그렇게 하겠습니다!
