### ISSUE TITLE
민서님이 제 플러터 파트에서 뭘 해야 하는지 적겠습니다!

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#62]
03_join
 - [ ] DB에 이메일이 이미 있는지 확인하는 로직 구현
 - [ ] 가입 조건 충족하면 DB에 저장하기

04_login
 - [ ] DB에 이메일이 존재하고 그에 맞는 비번인지 확인하는 로직 구현

06_result
 - [ ] 완성 이미지 업로드

09_modify
 - [ ] 닉네임 불러와서 textfield에 넣기

10_pwmodify
 - [ ] DB에서 기존 비밀번호 불러와서 입력한 것과 같은지 확인하기
 - [ ] 비번 변경 조건 충족하면 storedpassword = newpassword  DB 저장 로직 구현

12_unregister
 - [ ] DB의 비번과 맞으면 회원탈퇴하기 (DB 삭제)
 
 
 그리고 전체적으로 닉네임 코드에 불러오게 만들어야 할 것 같습니다.

**Comment by KIMSSI22** [comment]
알겠습니다~
