### ISSUE TITLE
6/3 개발 현황 

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#66]
지금까지 각자 파트에서 구현한 것 / 구현해야할 것 적어주세요

**Comment by dlcodns** [comment]
**[flutter]** 수정할게요
 - [x] 1번 페이지 구현
 - [x] 4번 페이지 구현
 - [x] 6번 페이지 구현

**[DB - mysql]**
 - [x] 유저 정보 datatable 구현(이후 민서님 xampp에 직접 만들어드림)
 - [x] 사진 정보 datatable 구현(미정)

**[로컬서버작업]**
 - [x] 페이지 이동 경로 합침(feature_local)

**Comment by KIMSSI22** [comment]
**[디자인]**
- [x] 완료

**[flutter]** 
- [x] 2번 페이지 구현
- [x] 3번 페이지 구현
- [x] 5번 페이지 구현

**[php]**
