### ISSUE TITLE
현재 imagepicker 문제점

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#69]
<img width="555" alt="image" src="https://github.com/dlcodns/OSP_Prediction/assets/107831875/13b2d2d4-233e-4d7a-bb78-7f2cc3676b25">

지금 imagepicker 구현하신거 보면 파일 자체는 안올라간거 아닌가요? 그냥 이미지의 주소만 받아놓은 것 같습니다. 
이미지 업로드 할 때 문제 생길 수도 있으니까 확인해보시는게 좋을 것 같습니다.

**Comment by KIMSSI22** [comment]
넵 알겠습니다.

**Comment by troymerai** [comment]
Xfile값에 이미지 파일을 담아서 문제 해결했습니다
