### ISSUE TITLE
feature_local 풀리퀘 올렸습니다!

### ISSUE THREAD

**Issue by dlcodns** [dlcodns/OSP_Prediction#74]

**Comment by troymerai** [comment]
<img width="941" alt="image" src="https://github.com/dlcodns/OSP_Prediction/assets/107831875/5a006ac2-19b1-467a-abbf-1858352f96da">

제꺼 풀리퀘 먼저 받아주시고 그다음에 메인을 feature_loacl로 merge 하시고 그다음에 다시 풀리퀘 날리셔야할 것 같습니다.

**Comment by dlcodns** [comment]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107669084/c6aa83e1-501c-409a-814d-1213f85c8889)
아직 그대로인데 어떻게 하는지 아시나요?

**Comment by dlcodns** [comment]
https://nana0.tistory.com/16 찾아보고 따라해보겠습니다

**Comment by troymerai** [comment]
<img width="863" alt="image" src="https://github.com/dlcodns/OSP_Prediction/assets/107831875/25ced6db-fb4a-40bc-a1a3-e1ce7cdbd335">

이거 아닌가요?

**Comment by troymerai** [comment]
해결하고 풀리퀘 날리시면 카톡 하나 부탁드리겠습니다

**Comment by dlcodns** [comment]
실수할 것 같아서 내일 아는 선배님한테 여쭤보고 하겠습니다. 일단 지우고 내일 다시 풀리퀘 해보겠습니다.

선배 말씀대로 하고 있으니까 지금 풀리퀘 아직 신경 안쓰셔도 돼요

**Comment by dlcodns** [comment]
feature_local, feature_flutter_LCU, feature_database 세 브랜치 feature_tmp에 merge 한 뒤에 main으로 풀리퀘 요청하도록 하겠습니다!!

**Comment by dlcodns** [comment]
풀리퀘 올렸습니다.
https://jihyewoo.tistory.com/195
feature_flutter_lcu의 root가 main에서 생성된 게 아니라서 위 티스토리 방식대로 rebase하느라 시간이 좀 걸렸습니다. 
그 과정에서 flutter 커밋(원래 158)이 두 배가 돼서 300이 넘었는데 커밋수 신경 안쓰셔도 될 것 같습니다ㅜㅜ
