### ISSUE TITLE
피팅룸 v1 풀리퀘 받아주세요

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#77]
#76 
1차 데모입니다

**Comment by troymerai** [comment]
[구현된 기능]

- [x] 회원가입/로그인
- [x] 이미지 선택 및 api 전송
- [x] 가공된 이미지 실시간 처리 후 반환
- [ ] 프로필

**Comment by troymerai** [comment]
디자인도 기존에 비해서 좀 변경됐습니다

**Comment by dlcodns** [comment]
네 확인했습니다. 풀리퀘 받았습니다!
