### ISSUE TITLE
리드미에 시연 영상 올리겠습니다

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#78]

**Comment by troymerai** [comment]
변환해보니 화질이 너무 안좋고 영상이 길어서 중간에 잘립니다.

**Comment by troymerai** [comment]
다른 방법 있는지 찾아보겠습니다

**Comment by dlcodns** [comment]
https://ktc7514.tistory.com/514
아이폰은 잘 모르겠고 갤럭시시면 스마트폰 연결해서 화면녹화기능 이용해도 좋을 것 같습니다. 영상 나눠서 넣어도 좋을 것 같아요
