### ISSUE TITLE
readme 파일 추가

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#86]
readme 파일에 각자 이메일 작성해주시거나 여기 남겨 주시면 제가 추가할게요. 
그리고 저희 license 내용 GPL 2.0 기반으로 제가 임의로 작성하긴 했는데 혹시 수정해야 할 부분 있으면 말씀 주세요.

**Comment by dlcodns** [comment]
redmond0412@gmail.com  입니다

**Comment by troymerai** [comment]
16alexandros57@gmail.com 입니다

**Comment by KIMSSI22** [comment]
추가했습니다.
