### ISSUE TITLE
기말 발표 준비

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#87]
![image](https://github.com/dlcodns/OSP_Prediction/assets/107696062/3281699b-fd4a-4d38-b1ee-4ae4e10d15a1)
교수님께서 기말 발표는 위 요소만 다 들어가면 된다고 하셔서 중간 때도 발표 했던 내용은 3 ~4분 정도로 좀 추리고 수정해서 발표하구요. 
시연 영상은 2 ~3 분 정도 하는 걸로 하고 또 교수님께서 의존성 부분은 언급해주면 좋다고 하셔서 그 부분도 포함하고 한계점, 개선방향을 2 ~3분으로 하면 시간에 맞게 발표 가능할 것 같아요.
혹시 발표 때 추가했으면 하는 내용 있으시면 말씀해주세요.

**Comment by KIMSSI22** [comment]
아 발표 시간은 8~10분이에요. 
그리고 발표 대본은 목금 시험이라 금요일 밤이나 토요일 오전에 올릴게요.

**Comment by dlcodns** [comment]
네 알겠습니다
