### ISSUE TITLE
시연 영상 의견말해주세요

### ISSUE THREAD

**Issue by troymerai** [dlcodns/OSP_Prediction#89]
제가 전에 보내드린 시연영상으로 하는거 어떤가요?
api에서 처리되는 과정도 보이고 제가 지금 윈도우 노트북이 없어서 갤럭시 폰에서 테스트를 못할 것 같습니다.

**Comment by dlcodns** [comment]
피팅 기능 보여주기에 좋은 것 같습니다 좋아요~!

**Comment by KIMSSI22** [comment]
저도 좋습니다.

**Comment by troymerai** [comment]
넵
