### ISSUE TITLE
기말 발표 ppt

### ISSUE THREAD

**Issue by KIMSSI22** [dlcodns/OSP_Prediction#92]
[기말발표(옾소프).pptx](https://github.com/dlcodns/OSP_Prediction/files/11712354/default.pptx)

기말 발표때 사용할 ppt 입니다. 
그리고 아래 대본 수정본 입니다.
저 근데 이 대본이 한 4분 50초 나오는데 영상이 2분 30초 정도잖아요. 그러면 한 40초 정도가 비어요. 혹시 더 추가할 아이디어 있으신분 계신가요?

**Comment by KIMSSI22** [comment]
안녕하세요. 칭찬주시조의 발표를 시작하겠습니다. 

목차를 소개하겠습니다.
먼저 지난 발표 내용을 정리(fitting room?, 필요성, 제안방법)하고 저희가 준비한 시연 영상을 시청한 후에 한계점과 개선방향에 대해 이야기하겠습니다.

저번 시간 제시한 프로젝트인 fitting room은 가상 피팅 서비스를 제공하는 앱으로 사용자가 앱을 이용하여 사용자의 이미지와 피팅해 보고 싶은 옷의 이미지를 보내면 이 사진들을 합성하여 마치 사용자가 해당 옷을 입은 듯한 이미지를 제공하는 기능을 가지고 있습니다.

그럼 저희가 이러한 서비스가 필요하다고 생각하게 된 이유를 설명하겠습니다. 오늘날 현대인들은 많은 결정과 일 처리를 공간에 제약받지 않고 수행할 수 있으며 그중 쇼핑 또한 아주 간편화되어 손쉽게 수행할 수 있는 종류 중 하나가 되었습니다. 

그럼에도 의상만큼은 다른 물품들에 비하여 오프라인 구매의 수요가 꽤 남아있는데 그 이유는 오프라인의 장점인 착장 가능의 여부입니다. 온라인 구매의 이유가 시간과 체력 절약 측면에서 더 뛰어나기 때문인데 막상 실제로 배달 온 상품을 입어보니 옷이 안 어울리거나 마음에 안 들어서 반품까지 이어지는 상황이 연출될 수 있습니다. 그렇게 되면 오히려 온라인의 장점이 사라지며 귀찮은 일은 생기고 시간을 버리게 되기에 여전히 오프라인 구매의 수요가 남아있습니다만 
여기 저희의 프로젝트, 가상 피팅 서비스를 이용한다면 이러한 온라인의 단점을 보안하여 현대인이 추구하는 편리함과 부족한 필요를 채워줄 수 있습니다. 게다가 현재 가상 피팅 서비스 시장은 vr 기기를 이용하여 제공하는 것에 과열된 상황입니다. 그렇기에 이용 조건 충족이 보다 어려운 vr이 아니라 앱으로 제공할 수 있게 한발 물러난다면 충분히 경쟁력 있다는 생각이 들었습니다. 따라서 여러 요소를 고려해 보았을 때 현시점에서 가장 적합한 서비스라고 판단되어 프로젝트를 시작하게 되었습니다.

그리고 fitting room의 제안방법으로는 다음 화면의 아키텍처를 보며 설명하겠습니다. 앱 환경의 클라이언트가 착장할 옷과 자신의 사진을 제공합니다. 그러면 그 이미지를 가지고 여기 세가지 딥러닝 모델을 이용해서 가상 피팅 이미지를 생성하고 이를 데이터베이스에 저장한 후 클라이언트에게 반환하는 과정을 통해서 서비스가 제공됩니다.
이를 구현하는 과정에서 프론트 엔드는 flutter로, 데이터베이스는 mysql, 회원가입, 로그인, 이미지 로직은 php를 이용하여 구현하였고 모델 서빙 기능은 fastapi로 구현하였습니다. 
그리고 딥러닝 모델은 다음과 같이 3가지 파이토치 모델들을 사용하였습니다. 해당 모델들의 자세한 의존성은 저희 readme 파일로 가시면 더 알아보실 수 있습니다.



그럼 이제 저희가 준비한 시연 영상을 시청하겠습니다.


저희 프로젝트의 한계점으로는 먼저 속도입니다. 아무래도 저희가 이번 프로젝트를 진행하면서 모두 개인의 laptop을 이용해서 진행하였기 때문에 코랩으로 머신을 돌린다고 해도 laptop만을 가지고 빠른 속도를 내기에는 어려움이 있었습니다. 그래서 영상에서 보신 것처럼 피팅된 이미지를 반환하기까지의 딜레이가 꽤 생겼고 속도의 한계점이 발생하였습니다.
그리고 또 다른 한계점으로는 상의에 국한된다는 것입니다. 이는 저희가 중간 발표 때도 언급 드렸다시피 하의는 피팅이 불가하다는 것인데. 저희가 이용하고 있는 딥러닝 모델 중 하나인 옷 합성 모델은 상의까지 기능을 제공하고 있고 저희는 이에 의존하고 있기 때문에 계속 이용할 시에는 하의 피팅이 어려운 한계점을 가지게 되었습니다.

그 다음은 개선방향입니다. 현재 fitting room의 회원가입이나 로그인 부분은 메일, 비밀번호, 사용자 이름으로 받고 있습니다. 그러나 추후 카톡이나 구글 등 대표적인 곳에서 제공하는 api를 이용하여 연동 로그인을 가능하도록 할 것입니다. 
그리고 시연 영상에서 공개된 fitting room은 대부분 주요 기능만 작동되고 있는 상황인데 저희가 생각하는 개선 방향으로는 부가적인 요소의 기능도 살려서 다른 앱의 구성과 비교하였을 때 최대한 따라갈 수 있을 정도로 올리는 것이 좋겠다고 생각하고 있습니다. 

그럼 지금까지 칭찬주시조의 가상 피팅 서비스, 피팅룸에 대한 발표를 마치겠습니다. 
감사합니다.

**Comment by troymerai** [comment]
교수님께서 저번 중간평가 때 problem, solution, input, output을 명시하라고하셨기 때문에 이 부분에 추가가 필요해보입니다.

[problem - 풀고자 하는 문제]
기존 글에서 갖고오면 될 것 같습니다.

[solution - 어떻게 풀지]
제안방법으로는 ~ 부터 갖고오면 될 것 같습니다.

[input - solution의 input]
시연 영상에서 넣을 두가지 데이터 카톡으로 보내드리겠습니다.

[output - solution의 output]
output은 시연 영상에서 보여주면 될 것 같습니다.

**Comment by KIMSSI22** [comment]
넵 감사합니다.

**Comment by troymerai** [comment]
그리고 한계점1에서 속도의 한계점은 빼는게 나을 것 같습니다. 
원래 해당 딥러닝 모델이 연산량이 많아서 시간이 오래걸리는겁니다. 노트북에서는 요청만 보내는거기 때문에 시간과는 상관이 없습니다.
차라리 실제 배포를 하지 못했다는 것으로 하는게 좋아보입니다.
해당 프로젝트에서 사용한 딥러닝 모델은 리눅스 + 쿠다 환경에서만 돌아가는 모델이기에 코랩이 아니면 리눅스 + 쿠다를 갖춘 환경이 필요했습니다. 하지만 딥러닝 모델도 처음 다뤄보는데다 리눅스 사용법은 더더욱 잘 몰랐기에 코랩을 선택했는데, 코랩은 런타임이 존재하기에 실제 배포를 하지 못했다는 한계가 있습니다.

**Comment by KIMSSI22** [comment]
아하 그렇군요. 수정하겠습니다.
